---
# tasks file for common
- name: set timezone to 
  timezone:
    name: "{{ t_z }}"
    
- name: Set a hostname
  hostname:
    name: "{{ inventory_hostname }}"

- block:
    - name: create swap folder
      file:
        path: "{{ swapfile_path }}"
        state: directory

    - name: create a swap file
      shell: fallocate -l {{ swap_size }} "{{ swapfile_path }}/swapfile"
      args:
        creates: /swapfile

    - name: set the correct permissions
      file:
        path: "{{ swapfile_path }}/swapfile"
        owner: root
        group: root
        mode: '0600'

    - name: make the file a swap file
      shell: mkswap "{{ swapfile_path }}/swapfile"
      when: ansible_facts.swapfree_mb == 0

    - name: enable the swap file
      shell: swapon "{{ swapfile_path }}/swapfile"
      when: ansible_facts.swapfree_mb == 0

    - name: add swap file to fstab
      mount:
        name: none
        src: "{{ swapfile_path }}/swapfile"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
